config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'books#index'
  devise_for :users
  resources :books
  patch '/books/:id/reserve', to: 'books#reserve', as: 'reserve'
  patch '/books/:id/cancel_reserve', to: 'books#cancel_reserve', as: 'cancel_reserve'
  patch '/books/:id/purchase', to: 'books#purchase', as: 'purchase'
  patch '/books/:id/cancel_purchase', to: 'books#cancel_purchase', as: 'cancel_purchase'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user, optional: true

    enum status: [:available, :reserved, :purchased]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy reserve cancel_reserve purchase cancel_purchase]

  # GET /books or /books.json
  def index
    @books = Book.where(status: :available)
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reserve
    respond_to do |format|
      if @book.update!(status: 1, user: current_user)
        format.js { render nothing: true }
        flash.now[:notice] = 'Book was successfully reserved!'
      else
        flash.now[:notice] = 'Book could not be reserved'
      end
    end
  end

  def cancel_reserve
    respond_to do |format|
      if @book.update!(status: 0, user: current_user)
        format.js { render nothing: true }
        flash.now[:notice] = 'The book is no longer reserved!'
      else
        flash.now[:notice] = 'The reserve could not be cancelled'
      end
    end
  end

  def purchase
    respond_to do |format|
      if @book.update!(status: 2, user: current_user)
        format.js { render nothing: true }
        flash.now[:notice] = 'The book was purchased!'
      else
        flash.now[:notice] = 'The book could not be purchased'
      end
    end
  end

  def cancel_purchase
    respond_to do |format|
      if @book.update!(status: 0, user: current_user)
        format.js { render nothing: true }
        flash.now[:notice] = 'The purchase was cancelled!'
      else
        flash.now[:notice] = 'The purchase could not be cancelled!'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :status, :isbn)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @books = @user.books.reserved
    @books_purchased = @user.books.purchased
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<tr id="book-<%= book.id %>">
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.status %></td>
    <td><%= book.isbn %></td>
    <div class="container">
        <td><%= link_to 'Reserve', reserve_path(book), remote: true, method: :patch, class: 'btn btn-outline-dark' %></td>
    </div>
</tr>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.number_field :isbn %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/cancel_purchase.js.erb
$('#book-<%= @book.id %>').replaceWith('<%= j render('books/book', book: @book) %>');

app/views/books/cancel_reserve.js.erb
$('#book-<%= @book.id %>').replaceWith('<%= j render('books/book', book: @book) %>');

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Isbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="books">
    <% @books.each do |book| %>
      <%= render 'books/book', book: book %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/purchase.js.erb
$('#book-<%= @book.id %>').replaceWith('<%= j render('books/book', book: @book) %>');

app/views/books/reserve.js.erb
$('#book-<%= @book.id %>').replaceWith('<%= j render('books/book', book: @book) %>');

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortalLibros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">

        <a class="navbar-brand">Library</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                    <li class="nav-item active">
                        <a><%= link_to 'My books', users_show_path(current_user) %></a> &nbsp;
                    </li>
                <% else %>
                    <li class="nav-item active">
                        <a><%= link_to 'Log in', new_user_session_path %></a> &nbsp;
                    </li>                
                    <li class="nav-item">
                        <a><%= link_to 'Sign up', new_user_registration_path %></a>
                    </li>
                <% end %>
            </ul>
        </div>
        
    </div>
</nav>

app/views/users/show.html.erb
<h1>Reserved Books</h1>

<table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Status</th>
        <th>Isbn</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody id="books">
      <% @books.each do |book| %>
        <tr id="book-<%= book.id %>">
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.status %></td>
            <td><%= book.isbn %></td>
            <div class="container">
              <td><%= link_to 'Cancel Reserve', cancel_reserve_path(book), remote: true, method: :patch, class: 'btn btn-outline-danger' %></td>
              <% if book.status == 2 %>
                <td><%= link_to 'Cancel Purchase', cancel_purchase_path(book), remote: true, method: :patch, class: 'btn btn-outline-danger' %></td>
              <% else %>
                <td><%= link_to 'Purchase', purchase_path(book), remote: true, method: :patch, data: { confirm: "Do you want to purhase #{book.title} ?"}, class: 'btn btn-outline-dark' %></td>
              <% end %>
            </div>
        </tr>
      <% end %>
    </tbody>
  </table>


<h1>Purchased Books</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Status</th>
        <th>Isbn</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody id="books">
      <% @books_purchased.each do |book| %>
        <tr id="book-<%= book.id %>">
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.status %></td>
            <td><%= book.isbn %></td>
            <div class="container">
              <% if book.status == 2 %>
                <td><%= link_to 'Cancel Purchase', cancel_purchase_path(book), remote: true, method: :patch, class: 'btn btn-outline-danger' %></td>
              <% else %>
                <td><%= link_to 'Purchase', purchase_path(book), remote: true, method: :patch, data: { confirm: "Do you want to purhase #{book.title} ?"}, class: 'btn btn-outline-dark' %></td>
              <% end %>
            </div>
            <div class="container">
              <td><%# link_to 'Show', book, class: 'btn btn-success' %></td>
              <td><%# link_to 'Edit', edit_book_path(book), class: 'btn btn-warning'  %></td>
              <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
            </div>
        </tr>
      <% end %>
    </tbody>
  </table>



  <td><%= link_to 'Back', books_path, class: 'btn btn-success'  %></td>